### ISSUE TITLE
Install issue?

### ISSUE THREAD

**Issue by rivyu123** [GeForceLegend/SEUS_PTGI_GFME#1]
Heya, I downloaded a fresh 2.1 HRR ptgi with this newest edited 1.10 jar, put them in the same folder, run the jar, move the new gfme zip into the shader folder and apply the new shader, but then the game ends up looking like its running no shaders at all (vanilla minecraft). Any tips?

**Comment by GeForceLegend** [comment]
GFME does not support Iris Shaders yet because of custon uniforms

**Comment by TofuHell** [comment]
Sorry to revive a dead thread but will there ever be iris support? i really like these shaders but its just not possible to use them at all on my modded games due to optifine load speeds,

**Comment by GeForceLegend** [comment]
> Sorry to revive a dead thread but will there ever be iris support? i really like these shaders but its just not possible to use them at all on my modded games due to optifine load speeds,

Strictly speaking, it's iris doesnt support GFME because iris doesnt support custom uniform yet. Iris 1.5 will support custom uniform, but i'v heard that GFME still not working correctly in iris 1.5 public test, hope they will fix this when it comes to public release.
