### ISSUE TITLE
Weird reflection light leaking underground in certain situations.

### ISSUE THREAD

**Issue by queenbiscuit311** [GeForceLegend/SEUS_PTGI_GFME#10]
For some reason when underground such as while mining there's sometimes light leaking when theres no light sources. I've tested this on both 1.19 and 1.18 on optifine and 1.19 on iris and its present on all of these.

[1.18.2 optifine H6.log](https://github.com/GeForceLegend/SEUS_PTGI_GFME/files/10378525/1.18.2.optifine.H6.log)

[latest.log](https://github.com/GeForceLegend/SEUS_PTGI_GFME/files/10378572/latest.log)

![2023-01-09_20 46 33](https://user-images.githubusercontent.com/88851292/211452944-a6797a20-ba08-4c18-9914-4a42e7ce081b.png)

![2023-01-09_21 07 13](https://user-images.githubusercontent.com/88851292/211452973-d037ee01-f1c4-44bb-aa52-d13873b3cafd.png)

**Comment by GeForceLegend** [comment]
Does the light leaking fix option works?

**Comment by queenbiscuit311** [comment]
I have them all on currently

**Comment by GeForceLegend** [comment]
Light from clouds by a oversight. Thx for catch it

**Comment by GeForceLegend** [comment]
Fixed in Release v1.12
