### ISSUE TITLE
Dark Nether

### ISSUE THREAD

**Issue by Vir7ualll** [GeForceLegend/SEUS_PTGI_GFME#11]
Not a bug, was just wondering if the nether could be adjusted to be brighter and way more visible like the one in PTGI 3, I like this shader a lot and I would love to not have to turn it off or switch when in the nether. Everything is dark and the nether is very difficult to thoroughly see in, that's all.

**Comment by GeForceLegend** [comment]
Down the water fog density

**Comment by Vir7ualll** [comment]
> Down the water fog density

Thanks for the response! It worked, surprisingly, never would have thought to check that at all. I wonder though if the option is separable, I tried out of curiosity and changing water fog in PTGI 3 does not affect nether lighting. Either way, thanks for the response and the hard work you done so far, and with that said, I consider this closed!
