### ISSUE TITLE
Colored light becomes yellow-ish at a certain distance from the light source

### ISSUE THREAD

**Issue by Aeldit** [GeForceLegend/SEUS_PTGI_GFME#12]
(Found the issue on Iris so I tried it on Optifine and it was still there | First 2 screenshots were taken on Optifine and the 2 others on Iris)
What it looks like normally :
![2023-01-16_18 34 56](https://user-images.githubusercontent.com/81476169/212737711-b9d85ef2-a22d-4a54-ba59-42c3abf14418.png)

What it looks like when we go further away from the light source :
![2023-01-16_18 35 14](https://user-images.githubusercontent.com/81476169/212737789-fa5c539d-fbb4-4347-947d-2df1c3318701.png)

Here is another example with soul lanterns, so blue light :
Normal :
![2023-01-16_18 41 33](https://user-images.githubusercontent.com/81476169/212738653-f00e82a4-cbde-440e-bd1e-4f15393ae61d.png)

Yellow or simply no light :
![2023-01-16_18 41 44](https://user-images.githubusercontent.com/81476169/212738687-f939a397-502d-43ec-b5e3-cc4fc9610a48.png)

Here is my F3 (I am on fabric with Iris for the second example but it also happens on optifine (standalone installation so no forge or fabric)
![2023-01-16_18 42 04](https://user-images.githubusercontent.com/81476169/212738891-46ad4944-2cb6-4bd5-9536-4796f49d71e5.png)

**Comment by GeForceLegend** [comment]
Work as intended. When blocks are too far away and is out of voxelization range, it will just use vanilla lightmap for block light. You can see same thing with vanilla PTGI before HRR2.1.
