### ISSUE TITLE
Strange grass block reflections

### ISSUE THREAD

**Issue by KismetPartisan** [GeForceLegend/SEUS_PTGI_GFME#13]
![2023-02-04_21 29 20](https://user-images.githubusercontent.com/95509438/216798663-f5be20dc-1359-4ee0-bc07-04f84c47735a.png)
![2023-02-04_21 28 07](https://user-images.githubusercontent.com/95509438/216798670-13c53553-ad97-4edf-bd4e-68b929a1e93f.png)

Tested on 1.19.3 Iris and Optifine

it's more noticeable when using a resource pack:
![2023-02-04_21 29 43](https://user-images.githubusercontent.com/95509438/216798701-106be1d1-4aee-4c5d-b341-2a3038ee0eaf.png)
![2023-02-04_21 30 26](https://user-images.githubusercontent.com/95509438/216798706-fac04df8-7881-4f4f-b792-5e725364032e.png)

**Comment by GeForceLegend** [comment]
Voxelization can only handle one texture per block, and there 2 layers on the side of grass block, one is the dirt and another is the top thin grass. Usually the texture get voxelized is the thin grass, so it might look strange in area with 0 alpha.
