### ISSUE TITLE
somethings

### ISSUE THREAD

**Issue by mfsa0** [GeForceLegend/SEUS_PTGI_GFME#15]
First of all, Thank you for your works. 

And I found somethings while using your PTGI GFME.

First, GFME doesn't work color light of candles.

![3](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/121943580/b7aa31d7-4f77-4fd1-9d34-7999025240d4)
It is PTGI HRR 3

![GFME](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/121943580/9a8b16cf-0747-4f4b-9872-1ad9bc77a85c)
And It is GFME.

can it be modified?

and Second is Light block(block.minecraft.light) block doesn't glow.

![Light Vanilla](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/121943580/d2fd5c2e-8d5f-4ac5-b30e-79730ea0a374)
It is Vanilla and most shaders glow light block.

![Light PTGI](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/121943580/c8669a55-880e-4d15-9796-906b375c2eb0)
and It is GFME.

It doesn't glow. I hope it will be modified.

AND There is block light bug in some resource packs. 
blocks don't glow
![Base Profile Screenshot 2023 05 16 - 22 33 34 35](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/121943580/d54976e6-d012-4a17-91f8-9443f0a44d69)
The block light is not bright enough on some resource packs.
This is a resource pack that looks exactly like the default resource pack(includes textures for server GUI). It has no different textures than Vanilla, but it does not have normal light support.

![Base Profile Screenshot 2023 05 16 - 22 33 48 98](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/121943580/f274f60b-0e2f-4f27-8710-5be1b38a2387)
and it is when I use another resource pack.

Thank you.

**Comment by GeForceLegend** [comment]
Closed as no reply for a long time
