### ISSUE TITLE
Texture issues in reflections

### ISSUE THREAD

**Issue by dkatzdev** [GeForceLegend/SEUS_PTGI_GFME#17]
Playing 1.20.1 with GFME 1.13 on the latest Iris Shaders 1.6.7, present on 1.6.5 as well

While using a 256x resource pack and the shader settings set appropriately, item icons are visible in glass reflections as shown below.

![2023-08-15_02 09 02](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/933792/e4fc6b44-c577-4a47-b486-de9c22d3cf14)

Resource packs are as follows:

![image](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/933792/1aa46ca9-0777-4090-b403-cafc46854d2b)

Let me know if I need to provide any additional information.

**Comment by dkatzdev** [comment]
Just to clarify, the version 1.12 of this resource pack is designed for 1.20.1, it it just the v1.12 of the pack

**Comment by dkatzdev** [comment]
Changing the texture resolution setting just changes the size of the icons. tested from x16 to x1024

**Comment by GeForceLegend** [comment]
Does this happen on Optifine? And does this happen without a resource pack?

**Comment by GeForceLegend** [comment]
So does this happen on Optifine?

**Comment by GeForceLegend** [comment]
Closed as no reply for a extremely long time
