### ISSUE TITLE
Weird texture bug with reflections on glass

### ISSUE THREAD

**Issue by PerfumedGoose82** [GeForceLegend/SEUS_PTGI_GFME#18]
This is similar to the other issue, I get random texture bugs on glass reflections, especially with tinted and stained glass. 

Hrr 2.1 gfme with no texture pack (optifine)
![2023-08-20_21 36 19](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/79411991/fe8aab89-c493-46e4-9f18-075c57fa3381)
Hrr 2.1 from seus with no texture pack (also optifine)
![2023-08-20_21 36 37](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/79411991/b1b95086-61de-4680-ac76-e2152088fcfd)
same order and pack from above just with a patrix 128x texture pack
![2023-08-20_21 37 51](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/79411991/5eb2c909-d821-4e81-b686-f411cb780905)
same order and pack from above just with a patrix 128x texture pack
![2023-08-20_21 38 12](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/79411991/94bc86d6-367a-444d-b8a6-6fa4ae6e41ad)
This also happens with sodium + iris (can provide screenshots if needed). While the tinted glass is borked in the original seus pack with it showing a water texture, the issue does not appear in regular glass using the seus pack but does on the gfme version.
I should probably also add that I am using the latest version of this (1.13) and 1.19.4 mc version

**Comment by GeForceLegend** [comment]
Does your texture resolution is set to correct value or "Auto"?

**Comment by PerfumedGoose82** [comment]
ahh, that was the issue. i had it set to a different resolution than the texture pack i was using. Thanks!
