### ISSUE TITLE
Vanilla Fog Nether Bug

### ISSUE THREAD

**Issue by 909oce** [GeForceLegend/SEUS_PTGI_GFME#19]
Just noticed this cause my nether had a 1 chunk render distance into black fog. Turns out if you have fog disabled in normal video settings it does this, changing it to "Default" fog setting fixes it. Interesting as it makes no difference on the overworld.

**Comment by GeForceLegend** [comment]
Are you using Iris? I cannot reproduce this on Optifine 1.20.1 I5.

**Comment by 909oce** [comment]
Yeah Iris

**Comment by GeForceLegend** [comment]
Maybe Iris does not set fogColor properly when fog is disabled? GFME's nether/the end fog is using fogColor, so there is no possible to fix it by shader side. You may want to contact Iris for support.
