### ISSUE TITLE
I can't install a shader in minecraft

### ISSUE THREAD

**Issue by Slavi4e** [GeForceLegend/SEUS_PTGI_GFME#22]
I watched a bunch of guides, did everything like in tutorials, installed a bunch of versions, I can't get a zip file with gfme, what can I do?

**Comment by Slavi4e** [comment]
> Есть ли какие-либо выходные данные при использовании инструментов командной строки для запуска этого jar-файла?

No, it writes a mistake, maybe I'm doing something wrong.

**Comment by GeForceLegend** [comment]
If you are sure you have installed Java, then using command `java -jar '.\SEUS_PTGI_HRR_Test_2.1_GFME_v1.14.jar' must print something. If the jar exists with some simple prints, it must be "Export success" or something wrong that directly tells you what to do. If it crashes and throwes an Exception, reply with the outputs, so I can know how to fix the crash.

**Comment by GeForceLegend** [comment]
You can using the "Tab" key to auto complete pathes in CMD or powershell. If your pathes are right, your command should be `java -jar 'C:\Users\(my user)\Downloads\Shaders For Minecarft\SEUS_PTGI_HRR_Test_2.1_GFME_v1.14.jar`

**Comment by Slavi4e** [comment]
writes this error... Error: Unable to access jarfile 'C:\Users\java

**Comment by GeForceLegend** [comment]
"Unable to access jarfile" Then your path must be wrong.

**Comment by Slavi4e** [comment]
Thank you for trying to help, but I didn't have the right version of SEUS ptgi hrr 2.1, I changed the version and it worked!
