### ISSUE TITLE
1.14渲染原版服中的文字实体会出现黑色背景

### ISSUE THREAD

**Issue by tsingyayin** [GeForceLegend/SEUS_PTGI_GFME#23]
# 问题概述
在使用1.14版本时，原版服的悬浮文字会出现意外的黑色背景。我不是很确定这个问题是何时开始出现的，我在此前长期使用1.10版本，未跟进期间的更新。
请问能考虑修复此问题吗？此问题过于影响环境美观程度。
此问题最先在IRIS环境中被发现，随后在Optifine环境中被复现。

# 有关配置信息
## 服务器
服务器版本：1.20.2 Purpur
文字所用插件：DecentHolograms

## 客户端
最先发现问题的Fabric IRIS 环境：Fabric 1.20.2
FabricAPI：0.90.0
可能有关的MOD环境：IRIS 1.6.10、Sodium 0.5.3、indium 1.0.27

按照要求复现的Forge OptiFine环境：Forge 1.20
Forge版本：46.0.14
Optifine版本: I5_pre5
无任何第三方Mod

# 有关详细配置信息和Bug表现
我准备了详细信息，这是1.10的Fabric+IRIS+Sodium 纯截图、Forge+Optifine F3截图和配置文件
[Fabric+IRIS+Sodium 纯截图](http://yxgeneral.cn/DirectFiles/TianyuServer/debug/eg_old.png)
[Forge+Optifine F3截图](http://yxgeneral.cn/DirectFiles/TianyuServer/debug/eg_old_optifine.png)
[配置文件](http://yxgeneral.cn/DirectFiles/TianyuServer/debug/shaderconfig_old.txt)
以及1.14的两个截图和配置文件
[Forge+IRIS+Sodium 纯截图](http://yxgeneral.cn/DirectFiles/TianyuServer/debug/eg.png)
[Forge+Optifine F3截图](http://yxgeneral.cn/DirectFiles/TianyuServer/debug/eg_optifine.png)
[配置文件](http://yxgeneral.cn/DirectFiles/TianyuServer/debug/shaderconfig.txt)

# 有关其他信息
此问题在Sonic Ether的原版HRR3中也存在，二者的表现一模一样。考虑到最近的项目更新引入了部分HRR3的内容，似乎您可以首先从那些内容入手。我从来没进行过类似的开发工作，不是很确定这个建议是否有用）

# 图像概要
下面的四个图像和上面六个链接中的四个图像是一样的，如果您能够在此处看到他们，则不必再转入上面的图像链接。我不确定直接在这里发布图片是否可能包含宣传服务器的不妥之处，如果您认为不合适，请告知我编辑并删除这一部分。
## 1.10版本的表现
![eg_old](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/77230422/f17e4edf-42ba-4307-b13b-9fbe8f97f374)
![eg_old_optifine](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/77230422/6ae188d2-cf25-4ca7-9c6f-0f704c4089f0)
## 1.14版本的表现
![eg](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/77230422/17884208-48cd-4137-a1a5-ffe0bc7a4340)
![eg_optifine](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/77230422/9647820e-6a45-4e55-91e1-37780b6b79d3)

**Comment by GeForceLegend** [comment]
这个属不属于bug还有待商榷。这个黑色的背景是原版就有的，目的是让文字显示更加清晰，并且PTGI在较长时间内一直会如同HRR3一样部分渲染这个黑色背景。
这个黑色背景渲染异常的原因是不写入深度，导致会被PTGI的物理大气覆盖，以及因为一些不明原因会被实体覆盖。
最近几个版本的GFME才出现的原因大概是因为我为了修复经验球不渲染的问题对实体透明的判定做了一些更改，这些判定是我自己为了避免信标光柱周围半透明部分的异常添加的，在修改后只作用于信标光柱着色器而不会影响实体的渲染。

**Comment by tsingyayin** [comment]
但是文字多的时候满屏黑条和完美的光追效果相比确实很不协调，尤其服务器上会经常性遇到大量的文字多的环境。

私以为应该为画面总体美观部分牺牲文字可视程度（指像以前那样完全不渲染黑色背景），或者稍微麻烦一点，开创光影修改文字背景透明度的先河。

**Comment by GeForceLegend** [comment]
找了个办法区分经验球和文字背景，能在1.20.1和1.12.2上正常工作，1.14应该也能正常。会在下一个版本更新。

**Comment by tsingyayin** [comment]
是您光影的1.14啊）
