### ISSUE TITLE
樱花花瓣光照效果异常

### ISSUE THREAD

**Issue by tsingyayin** [GeForceLegend/SEUS_PTGI_GFME#24]
# 问题概述
在使用GFME1.14版本时，樱花花瓣在没有接受阳光照射时显示错误的全黑色阴影。有阳光照射时存在异常的黑色边框阴影

此问题最先在IRIS环境中被发现，随后在Optifine环境中被复现。

# 有关配置信息
## 客户端
最先发现问题的Fabric IRIS 环境：Fabric 1.20.2
FabricAPI：0.90.0
可能有关的MOD环境：IRIS 1.6.10、Sodium 0.5.3、indium 1.0.27

按照要求复现的Forge OptiFine环境：Forge 1.20
Forge版本：46.0.14
Optifine版本: I5_pre5
无任何第三方Mod

# 图像概要
![屏幕截图 2024-01-21 224428](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/77230422/d872c55f-75be-424c-b4df-d9c5a597fcf0)
![屏幕截图 2024-01-21 224418](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/77230422/9d535c65-38be-43cf-96f9-3aa9ff9c48a4)
![屏幕截图 2024-01-21 224343](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/77230422/4e518108-3a9d-473c-9b17-f68e1899bf47)
![屏幕截图 2024-01-21 224434](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/77230422/8889caaf-02d5-4739-b45a-e054dd309ade)

**Comment by GeForceLegend** [comment]
Optifine 1.20.1 I6 pre6 无法复现

**Comment by tsingyayin** [comment]
抱歉，我在启动器里选择错了版本，Optifine确实无法复现，鉴定为IRIS抽风
