### ISSUE TITLE
Torches placed on the side of a block doesn't emit light.

### ISSUE THREAD

**Issue by Marselord** [GeForceLegend/SEUS_PTGI_GFME#27]
![2024-02-19_23 54 51](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/13491526/44fdbe2d-6adf-4ddf-9507-63fa26f2578f)
![2024-02-19_23 54 59](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/13491526/4d4cf22b-6718-40d0-b545-5032a6f3b2d9)
![2024-02-19_23 55 04](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/13491526/9dbd57db-fad5-4d12-b489-826d82ac1f9d)
![2024-02-19_23 55 09](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/13491526/65266679-992e-4d72-94c3-7d9d0c4750e8)

Soul torches are not affected.
Minecraft version 1.20.2
Iris version 1.6.12
![2024-02-20_00 00 08](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/13491526/4126aba4-6ffc-4f1a-bb77-30f5f5bce276)

**Comment by GeForceLegend** [comment]
Caused by Iris's issue on parsing block.properties
