### ISSUE TITLE
Reflections on Iris v1.7.0 look off regardless of the ressource pack

### ISSUE THREAD

**Issue by SpidFightFR** [GeForceLegend/SEUS_PTGI_GFME#28]
Hey there.
I've noticed that reflections are a bit off, regardless of the resource pack used... Any idea how to solve this ?
![2024-05-07_23 02 39](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/60798703/81637ff6-e3fa-4d94-acdb-464b7d70ec4e)

![2024-05-08_19 57 35](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/60798703/06599e46-57b1-47c7-855c-dd3070af682e)

![2024-05-09_14 29 11](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/60798703/a7b64674-d403-4e7d-84d8-52e67a670177)

My config:

CPU: R7 7800X3D
GPU: RX 7900XTX
Iris 1.7.0
Sodium : 0.5.4
Minecraft 1.20.4

**Comment by GeForceLegend** [comment]
Did you enabled `Anisotropic filter` in mod setting or driver setting? If not, did you set `Texture resolution` in shader setting to auto or the value of resource pack you are using?

**Comment by SpidFightFR** [comment]
> Did you enabled `Anisotropic filter` in mod setting or driver setting? If not, did you set `Texture resolution` in shader setting to auto or the value of resource pack you are using?

i don't remember i did lemme double check but iirc those checks are correct...

**Comment by asyntote** [comment]
Hi all, if can help, I had the same problem some times, a lot of time ago, with a clean Seus PTGI 2.1 too.
I think it is a "bug" inside the original Seus code.

**Comment by SpidFightFR** [comment]
> Hi all, if can help, I had the same problem some times, a lot of time ago, with a clean Seus PTGI 2.1 too. I think it is a "bug" inside the original Seus code.

yes indeed E12 does the same thing, i just tried that... that sucks...
Welp thank you everyone for your help, i'm closing the issue.

**Comment by GeForceLegend** [comment]
This should not happen if anisotropic is not enabled and texture resolution is set to correct value, otherwise there must be tons of similar bug report (not only GFME, but also unedited PTGI) before.

**Comment by SpidFightFR** [comment]
> This should not happen if anisotropic is not enabled and texture resolution is set to correct value, otherwise there must be tons of similar bug report (not only GFME, but also unedited PTGI) before.

i checked, i found no way for me to change the anisotropic filtering so i assume it's the default value...
