### ISSUE TITLE
TACZ support?

### ISSUE THREAD

**Issue by CFog1** [GeForceLegend/SEUS_PTGI_GFME#31]
So when I use Timeless and classics zero the guns' visuals break and look weird hopefully this gets fixed

![image](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/144547531/460609bc-c4bb-4a72-9336-582c940d1c5b)

**Comment by GeForceLegend** [comment]
It's just HRR's temporal upscale cannot handle moving held item perfectly. Nothing can do with that.

**Comment by CFog1** [comment]
:C
