### ISSUE TITLE
[Feature Request] Light-emitting blocks surrounded by full-height blocks should emit light on their surfaces

### ISSUE THREAD

**Issue by helpimnotdrowning** [GeForceLegend/SEUS_PTGI_GFME#32]
This is not a bug report!

Currently, blocks like glowstone, when surrounded on an axis by other (non-light-emitting) full-height blocks, do *not* emit light on their surfaces:
![image](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/35247379/4fe7d283-e3dd-40b3-8043-578fa366584a)

Personally, this ends up looking strange, since blocks that light up their surrounding walls keep the entire floor dark (apart from reflected light):
![image](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/35247379/280f1e67-fd75-4966-a3db-a5e08280f858)

Ideally, it would look (something) like this, simulated with melting 7-layer snow blocks:
![image](https://github.com/GeForceLegend/SEUS_PTGI_GFME/assets/35247379/b7a1d1c4-f9dd-4daa-a5b4-12017afe846d)

Would a feature like this be possible?

**Comment by GeForceLegend** [comment]
It's not possible as ground surfaces around it cannot have any ray connect to the light block.
