### ISSUE TITLE
Nearby DH shadows still breaking even with "DH Shadow Fix" enabled

### ISSUE THREAD

**Issue by TicTecOfficial** [GeForceLegend/SEUS_PTGI_GFME#33]
title says everything
![image](https://github.com/user-attachments/assets/87812aea-9462-4c6c-8453-5227f2368a30)

**Comment by GeForceLegend** [comment]
This is unable to fix, due to shadow distortion function and the way DH merging vertex. And that's the main reason most DH pack does not provide DH shadowmapping.
