### ISSUE TITLE
Can you create a custom blockGI generator? 

### ISSUE THREAD

**Issue by ENDNULL** [GeForceLegend/SEUS_PTGI_GFME#34]
When I place the mod blocks(by custom model),I find that they use the full block's GI ,and show a wrong appearance.
Sonicether says he will create one,but seems he stops his work after it : (.

![QQ_1721471424138](https://github.com/user-attachments/assets/f7c56194-1ef2-4761-9892-65fc657b4046)

**Comment by GeForceLegend** [comment]
No new shapes can be added into GFME now, but if you want to add mod blocks with same shape as existing hardcoded one, just adding them to block.properties. With a bit knowledge on properties file format, and Optifine's blockID and blockstate format, you can add most common mod blocks into it, tho it may take some time.
