### ISSUE TITLE
一个Iris上的光色问题

### ISSUE THREAD

**Issue by tsingyayin** [GeForceLegend/SEUS_PTGI_GFME#35]
> 知道你不喜欢`iris`，但现在有一个神奇的问题 ）

绿宝石块与青金石块的光线颜色似乎在`iris 1.7.3`中不正确。
# 版本情况
* 光影版本：`DH Test`
* 发生问题的版本：`Fabric 1.21 0.100.7` `iris 1.7.3` `DistantHorizons 2.1.2-a`
* 没有问题的对照：`Forge 1.20 46.0.14` `OptiFine_I5_pre5` **没装地平线**

# 问题参照
* 被抹去的信息含有隐私内容，所欠缺的版本号已在上文提供
## 发生问题的版本
![2024-07-22_10 44 50](https://github.com/user-attachments/assets/74ed0eaa-7ce2-46b4-ad16-cc7fa90ffa45)
## 没有问题的对照
![2024-07-22_10 43 46](https://github.com/user-attachments/assets/3da6f345-da14-4a3b-ac9e-bacaf8cca479)

# 其他备注
1. 本来想用`Forge 1.21`+`OptiFine`+`DistantHorizons`测试的，但没找到`OptiFine`更新，所以用的1.20，也没装地平线。
2. 光影版本`v1.10`在以上两个对照环境中也存在这个现象
3. 另外测试了`Fabric 1.20.2`+`Iris 1.6.10`版本下光影版本`v1.10`和`DH Test`，光色是**正常**的。所以个人觉得**很有可能是新版`iris`的锅**，但不知道这个是`iris`的bug还是`iris`又改了什么玩意导致需要开发者来适配）

4. **红石块颜色在上述所有MC版本与光影版本中都是正常的**

# 光影所用配置文件
```plain
#Mon Jul 22 10:29:38 CST 2024
BLOOM_AMOUNT=0.1
EXPOSURE=0.7
FULL_RT_REFLECTIONS=true
GI_LIGHT_BLOCK_INTENSITY=10.0
GI_LIGHT_TORCH_INTENSITY=10.0
SATURATION=1.1
SUNLIGHT_BRIGHTNESS=4.0
TONEMAP_CURVE=1.0
TORCHLIGHT_COLOR_TEMPERATURE=3750
VOLUMETRIC_LIGHT_STRENGTH=0.5
```

**Comment by GeForceLegend** [comment]
在使用
DistantHorizons-2.1.2-a-1.21-neo-fabric
fabric-api-0.100.4+1.21
indium-1.0.34+mc1.21
iris-1.7.3+mc1.21
sodium-fabric-0.5.11+mc1.21
的情况下无法复现
![20240722-123156](https://github.com/user-attachments/assets/a1107f14-760b-4518-81b9-abdadbd6f35e)

**Comment by tsingyayin** [comment]
我认为这简直不可理喻

我发现这个问题只在进入我自己的个人服务器时发生。也就是说，直接启动到单人存档色彩是正常的，但是一旦加入到我的服务器，色彩就会变成白的，并且即使回退到单人存档也是如此，除非重新启动游戏。

我甚至在本地重新配置了一个服务器，发现这个本地配置的服务器并不会发生这个现象。我还考虑过是否和DH缓存的服务器数据量有关，于是我删除了数据，甚至是完全移除了DH，都发现这个现象只在进入我的个人服务器后发生。

我不清楚接下来是否还有必要继续向您展开这个issues，因为事已至此恐怕问题有些复杂，如果您有兴趣的话，我在您的Bilibili私信发送了我个人服务器的地址以及属于您的相关登录信息。或者您也可以直接关闭此issues。

**Comment by tsingyayin** [comment]
经过私聊，此问题被认为和`Iris`有关。

此问题的直接原因是服务器应用的资源包中贴图量太多太杂，超出了`Iris`总纹理集的精度范围，且`Iris`未能在退出服务器后卸除相关数据导致继续产生影响。

通过裁剪服务器资源包，重做大量内容以精简、合并贴图，此问题已经被解决。

此问题是一个很不常规的极端问题，解法可供参考。

关键词：`server` `color of light` `iris` `color` `texture`
