### ISSUE TITLE
Add LabPBR support

### ISSUE THREAD

**Issue by nukmuk** [GeForceLegend/SEUS_PTGI_GFME#36]
I tried turning on Smoothness as Roughness and changing the specular channels to "g", "r" and "a", but it still looked way off. Seems like almost all resource packs use the LabPBR format nowadays.

**Comment by GeForceLegend** [comment]
LabPBR is still using r as smoothness, so all your setting is just making it far away from LabPBR. Default setting is very similar to LabPBR, excepting LabPBR using g as F0 and hardcoded metal, but not metalness.
