### ISSUE TITLE
Support for Custom Light Souces

### ISSUE THREAD

**Issue by djinnbanter** [GeForceLegend/SEUS_PTGI_GFME#37]
Currently, the shader does not accurately render light sources from modded or custom blocks. Is there any way to implement support for custom light blocks similar to the way Bliss/Photon shaders handle them?

**Comment by GeForceLegend** [comment]
Bliss/Photon are using vanilla block light levels, so ti's much easier for those shaders to handle block light sources. For voxel path tracing shaders, you can try adding mod light blocks into `shaders/block.properties`, but **remember it may not work as intended**
