### ISSUE TITLE
Physics Mod smoke position is changing with camera movement

### ISSUE THREAD

**Issue by smiRaphi** [GeForceLegend/SEUS_PTGI_GFME#38]
https://github.com/user-attachments/assets/f315c564-2abb-4582-bb04-d9a511cbf7ae

Minecraft 1.21/Iris 1.7.3 & Minecraft 1.19.4/Optifine HD U I4
Physics Mod V171 (also tested on V170 but only with Iris)

I also have other mods in that clip but I've also tested it without them.

**Comment by GeForceLegend** [comment]
Does this happen on other shadesr?

**Comment by GeForceLegend** [comment]
I cannot see this with `physics-mod-pro-v170d-fabric-1.21.0` and `iris-1.7.3+mc1.21`
![2024-08-13_13 11 48](https://github.com/user-attachments/assets/4ce39f12-dba1-4d07-bc39-de51aa2a490e)

**Comment by GeForceLegend** [comment]
Looks like this happens on most shader that is using super sampling, so this should be a thing related to physics mod, but not shader mod or shaderpacks.

**Comment by smiRaphi** [comment]
> Does this happen on other shadesr?

just tried it with these and it only happened with photon & the ptgi shaders
![image](https://github.com/user-attachments/assets/d69a890e-4c78-4f5f-8cdb-0acd0a4edee8)
