### ISSUE TITLE
Oculus and/or Iris Support

### ISSUE THREAD

**Issue by TofuHell** [GeForceLegend/SEUS_PTGI_GFME#4]
Hello again, I really love this Shader is there any plan to add Oculus (please) or Iris Support now that they support PBR?
Right now with Oculus and SEUS GFME the screen becomes a gray blob.

https://i.imgur.com/ybITwuT.png
https://i.imgur.com/ybITwuT.png

Both these taken with only forge, oculus 1.2.8 and GFME (latest) enabled on 1.19.2

Again this shader is amazing better then paid ones.

**Comment by TofuHell** [comment]
Hello sorry I

**Comment by Inrixia** [comment]
@TofuHell You mention it was broken in a recent update. Does this mean this shader is working in a previous version of oculus?
