### ISSUE TITLE
better night vision

### ISSUE THREAD

**Issue by rhjdvsgsgks** [GeForceLegend/SEUS_PTGI_GFME#40]
hi

i found that current solution for night vision will make the shadow of moon light (almost) disappear, everything looks like unshadered at all. i thought it maybe a bug of iris or my driver. but after some comparession i discovered that it actually caused by 
```glsl
       colorTemp+=(nightVision*0.05+1e-4)*(1.-v.metalness);
```
at `shaders/deferred12.fsh`.

is it a intended behavior? if no, i would suggest to make it become a factor of gamma, or just keep the original ptgi behavior to change `NIGHT_BRIGHTNESS`

![img](https://github.com/user-attachments/assets/8ca742e7-6519-4d2c-af17-9002ad265f4d)

**Comment by GeForceLegend** [comment]
Work as intended.

**Comment by GeForceLegend** [comment]
They are not disappeard, just become less obvious as night vision added some direct brightness on everything.
