### ISSUE TITLE
Translucent/Almost invisible particle effects

### ISSUE THREAD

**Issue by darock830** [GeForceLegend/SEUS_PTGI_GFME#41]
Certain particle effects are nearly invisible, especially in light. Things like potion effects are fine.
The problematic particle effects are the ones that mods like to utilize (e.g., Ars Nouveau, Nature's Aura, etc.). They are the glowy looking slightly translucent light orbs (becoming almost invisible when this shader is active)

The latest log is attached.
[latest.log](https://github.com/user-attachments/files/17535104/latest.log)

I apologize if this is out of your hands. Just trying to find a solution. :)

**Comment by GeForceLegend** [comment]
Particles are hard to render well in deferred pipeline shaders, especially some particle in mods that used to create their own visual effects.
