### ISSUE TITLE
Global Illumination takes a hit compared to PTGI HRR 2.1

### ISSUE THREAD

**Issue by GormAuslander** [GeForceLegend/SEUS_PTGI_GFME#44]
First of all, thank you for continuing to work on this shader

The issue I'm having is that Sonic Ether's global illumination is much brighter and softer than I'm seeing in the new GFME. I've attached images where you can see that in shaded areas, the bounce light is less able to illuminate, and the shadow boundaries are sharper rather than blended. These are both stock settings, except I've corrected torch light temp, bloom, and saturation strength, both to the same degree. I've tried increasing the RT samples, secondary GI, exposure, gamma, and decreasing shadow strength to try and match the old lighting but nothing seems to get there.

Any help would be appreciated because this is the sole reason I use SEUS over any other pack.

GFME
![2024-11-10_15 29 10](https://github.com/user-attachments/assets/324ec14c-cdab-48ba-8e5e-4ffe44d134aa)
HRR 2.1
![2024-11-10_15 29 20](https://github.com/user-attachments/assets/5aad9896-7fb8-4c25-bd2f-a83655d13130)
GFME
![2024-11-10_15 31 17](https://github.com/user-attachments/assets/9110545f-a391-4fee-9997-d92346630255)
HRR 2.1
![2024-11-10_15 30 52](https://github.com/user-attachments/assets/8aae3cb5-7de5-4b05-b5a9-bff176e9b8ac)

**Comment by GeForceLegend** [comment]
I guess you want to disable `Shader Options > Raytracing > Full Cave GI Leak Fix` and `Shader Options > Shadow > Sunlight Leak Fix`

**Comment by GormAuslander** [comment]
With both disabled, I observe no change

**Comment by GeForceLegend** [comment]
This is how it looks like with both disabled and both enabled on my device.
![2024-11-11_23 39 03](https://github.com/user-attachments/assets/c6a09111-f202-42f1-8bf4-a7ca417835f3)
![2024-11-11_23 38 40](https://github.com/user-attachments/assets/5f8a025b-449f-4378-b370-0783da5d1087)

**Comment by GormAuslander** [comment]
That appears to demonstrate a large scale rendering issue, while mine is a confined area which receives less light from bounce. I would send images, but they look exactly the same as above after making the suggested changes

**Comment by GormAuslander** [comment]
> You can send a world that can see such thing, or check your mods first?

I'm sorry, I'm not sure I understand what you're asking. Can you explain?

**Comment by GormAuslander** [comment]
> maybe the light doesn't bounce enough or something
That was the suggested reason in my original post. The seus HRR 2.1 has a slider to adjust the bounce, but it's gone in GFME

**Comment by LimeDragonBoi** [comment]
just add it back 😎

**Comment by GeForceLegend** [comment]
> > You can send a world that can see such thing, or check your mods first?
> 
> I'm sorry, I'm not sure I understand what you're asking. Can you explain?

Send the world (or save, a folder in `.minecraft/saves`) in your image. Do not rely on machine translator if you are bad at English, AI translator like GPT might be better.

**Comment by GormAuslander** [comment]
> Do not rely on machine translator if you are bad at English

Lol, I'm a native speaker, but thank you for your consideration. My confusion was due to the structure of your sentence being very broken and difficult to parse. However, your clarification was sufficient and I understand now.

Unfortunately it's two separate worlds, and both are very large. However, I can easily set up a little demo world and procure similar results and send that to you.

**Comment by GormAuslander** [comment]
I have the world download here, which has copied the two rooms I was in. I specifically wanted to highlight this area, where you can see the wall lit up by reflected light from the floor in HRR, but not in GFME
![2024-11-19_19 43 37](https://github.com/user-attachments/assets/c43ed10c-289d-4db0-99b0-ada3992d61ac)
![2024-11-19_19 44 30](https://github.com/user-attachments/assets/b9cd4207-37
[New World.zip](https://github.com/user-attachments/files/17824016/New.World.zip)
6a-45bc-aaf8-0f1f22f3fd5f)

**Comment by LimeDragonBoi** [comment]
Can you make a preset that makes the GFME shader look like HRR 2.1?

**Comment by GormAuslander** [comment]
Yeah, that's unfortunate because the real excitement about this project was the DH support. Is there any way to add these customizations back in as optional?

**Comment by GormAuslander** [comment]
> "High" GI trace length in PTGI HRR 2.1 is just 80 maximum steps, while you are using 160 maximum step in GFME.
> 
> And, voxelization radius in HRR 2.1 only about 80 blocks (same as minimum shadowmap resolution option in GFME), which means it cannot hit a huge part of this building, which makes sky lighting become much more than expected.

Does that explain why it happens at night too though? 
![2024-11-23_17 57 07](https://github.com/user-attachments/assets/833669d4-25eb-4043-9570-0b881012e6f6)
![2024-11-23_17 57 26](https://github.com/user-attachments/assets/f904a11e-3e8e-419f-a39d-4503ccd2ea39)
The block light intensities are the same
