### ISSUE TITLE
shader bug, looks like incompatibility with some mod

### ISSUE THREAD

**Issue by Krounder** [GeForceLegend/SEUS_PTGI_GFME#53]
shader bug, looks like incompatibility with some mod
![Untitled](https://github.com/user-attachments/assets/1c954f6c-4382-4b95-a0c2-dcca7e9f3a0b)

**Comment by Krounder** [comment]
UPD caused by auto texture resolution

**Comment by NizeroXs** [comment]
> ошибка шейдера, обнаружилась несовместимость с каким-то модом

This is an issue with the new version of IRIS. You simply need to turn off the "Ray-traced shadow" setting, which is located in the shader settings - shadow.

**Comment by NizeroXs** [comment]
@GeForceLegend Should we also contact the Iris developers for fixing this setting?

**Comment by Krounder** [comment]
> @GeForceLegend Should we also contact the Iris developers for fixing this setting?

If it's possible to fix something, why not try?

**Comment by NizeroXs** [comment]
By the way, disabling ray-traced shadows does not affect the quality of shadows or performance.

**Comment by Krounder** [comment]
> By the way, disabling ray-traced shadows does not affect the quality of shadows or performance.

Then why its enabled by default?

**Comment by NizeroXs** [comment]
> Then why its enabled by default?
I don't know, honestly. But this setting has always been problematic on IRIS, for example, it also causes a bug with "rectangular" shadows in the distance. And I personally don't know how it works, but in my tests I didn't see any difference. We'll wait for GeforceLegend's answer.

**Comment by GeForceLegend** [comment]
Only exist on Iris 1.8.1 for Minecraft 1.21.1 on NeoForge. It's an issue of Iris but not mine.
