### ISSUE TITLE
The LOD system for textures above 128x isn't working

### ISSUE THREAD

**Issue by NizeroXs** [GeForceLegend/SEUS_PTGI_GFME#54]
Below, I provide screenshots; both have the same shader settings, but the first screenshot is 128x, and the second is 256x. The blurriness of 128x is clearly visible, as well as the distance at which the rails lower the quality even more. At 256x, the quality is consistently high everywhere, which results in poor anti-aliasing on the textures.

I'm using IRIS 1.8.1 on Fabric 1.21.1, and I've noticed this issue for a long time. On all versions of Iris for 1.20.1, it worked the same way. I double-checked on a clean 1.21.1 Forge with OptiFine, and it's exactly the same there.

Can you fix this or advise me on how to resolve it?

![2024-12-27_14 35 24](https://github.com/user-attachments/assets/14e2eb27-b78e-4e17-8860-150f2cd26a51)
![2024-12-27_14 35 04](https://github.com/user-attachments/assets/0b08db93-5bb6-4d65-ae5d-12d43d9768c5).

**Comment by NizeroXs** [comment]
I even tried setting LOD below 1.0 in the config; with 128x, all textures were terribly blurry even up close, and with 256x, nothing changed.

**Comment by GeForceLegend** [comment]
Texture lod is directly merged from HRR3. If this also exists in HRR3, this is not mine duty.

**Comment by NizeroXs** [comment]
> Текстура lod напрямую объединена с HRR3. Если это также существует в HRR3, это не моя обязанность.

Is it completely impossible to fix it?

**Comment by NizeroXs** [comment]
> Texture lod is directly merged from HRR3. If this also exists in HRR3, this is not mine duty.

I'm testing HRR 3 and see that it has the same issue. It's very disappointing, as I really wanted to play with high-resolution textures

**Comment by GeForceLegend** [comment]
Minecraft only generates 4 mipmap for block texture, so with 256x texture, it's maximum lod is 16x, which matches the vanilla look in your image. Nothing I can do here.
