### ISSUE TITLE
HRR 3 support

### ISSUE THREAD

**Issue by Starglidee** [GeForceLegend/SEUS_PTGI_GFME#55]
Is there any plan to support hrr 3? They have very good color correction, shadows and light (eye) adaptation, compared to 2.1
![IMG_7550](https://github.com/user-attachments/assets/3fda0316-d709-471e-ad50-24679b336fca)
![IMG_7549](https://github.com/user-attachments/assets/61626ab9-bb6a-4427-8a55-d1bad44952e3)

**Comment by GeForceLegend** [comment]
Already merged most changes from HRR3. Merging remaining thing will break low version compatibility.

**Comment by Starglidee** [comment]
> Already merged most changes from HRR3. Merging remaining thing will break low version compatibility.

Okay, but is it possible to add advanced color correction settings? (contrast and rgb sliders?)

**Comment by deezhizyu** [comment]
@GeForceLegend 
is it possible to install your modification for HRR 3 now?
