### ISSUE TITLE
screen space gi tracing breaks the shader on iris 1.5 beta 2

### ISSUE THREAD

**Issue by Taiyou06** [GeForceLegend/SEUS_PTGI_GFME#6]
![image](https://user-images.githubusercontent.com/77050201/209845722-17ec1150-ddcf-44b2-95e7-49438249cb92.png)

**Comment by Taiyou06** [comment]
(idk if this is a iris issue or not)

**Comment by GeForceLegend** [comment]
known as also affect optifine. do not use that until next version.
