### ISSUE TITLE
fix partricles render

### ISSUE THREAD

**Issue by Fefedu973** [GeForceLegend/SEUS_PTGI_GFME#7]
the particles are not rendered in the right place sometimes and they are fucked up.
![image](https://user-images.githubusercontent.com/80718477/210400183-aacf1325-9ac4-4ee7-9337-21b7ec323037.png)
for exemple here the particles are transparent with the water

**Comment by GeForceLegend** [comment]
Mod support is never an important thing for minecraft shaders, especially path tracing shaders

**Comment by Fefedu973** [comment]
> Mod support is never an important thing for minecraft shaders, especially path tracing shaders

this happens even without a mod I just took the first image that came to hand to illustrate

**Comment by Fefedu973** [comment]
> Mod support is never an important thing for minecraft shaders, especially path tracing shaders

this happens even without a mod I just took the first image that came to hand to illustrate
